# lstmcpipe generated config from PathConfigProd5Trans80 - 2024-02-14

workflow_kind: lstchain

# prod_id ex: local_no_n_islands. Default; v00 (if key left empty or None)
prod_id: whatagreatprod

source_environment:
  source_file: /fefs/aswg/software/conda/etc/profile.d/conda.sh
  conda_env: lstchain-v0.9.13

slurm_config:
# dpps is the default account for lstanalyzer - other users should use aswg
  user_account: dpps
lstmcpipe_version: 0.10.3
prod_type: PathConfigProd5Trans80
stages_to_run:
- r0_to_dl1
- train_test_split
- merge_dl1
- train_pipe
- dl1_to_dl2
- dl2_to_sensitivity
- dl2_to_irfs
stages:
  r0_to_dl1:
  - input: 
      /fefs/aswg/data/mc/DL0/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing
    output: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing/whatagreatprod
  - input: 
      /fefs/aswg/data/mc/DL0/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/off0.0deg
    output: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.0deg
  - input: 
      /fefs/aswg/data/mc/DL0/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/off0.4deg
    output: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.4deg
  - input: 
      /fefs/aswg/data/mc/DL0/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing
    output: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod
  - input: 
      /fefs/aswg/data/mc/DL0/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing
    output: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing/whatagreatprod
  train_test_split:
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing/whatagreatprod
    output:
      train: 
        /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing/whatagreatprod/train
      test: 
        /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing/whatagreatprod/test
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.0deg
    output:
      train: 
        /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.4deg/train
      test: 
        /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.4deg/test
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.4deg
    output:
      train: 
        /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.4deg/train
      test: 
        /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.4deg/test
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod
    output:
      train: 
        /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod/train
      test: 
        /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod/test
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing/whatagreatprod
    output:
      train: 
        /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing/whatagreatprod/train
      test: 
        /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing/whatagreatprod/test
  merge_dl1:
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing/whatagreatprod/train
    output: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing/whatagreatprod/dl1_gamma-diffuse_whatagreatprod_train.h5
    options: --no-image
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod/train
    output: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod/dl1_proton_whatagreatprod_train.h5
    options: --no-image
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.4deg/test
    output: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.0deg/dl1_gamma_whatagreatprod_test.h5
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.4deg/test
    output: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.4deg/dl1_gamma_whatagreatprod_test.h5
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing/whatagreatprod/test
    output: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing/whatagreatprod/dl1_electron_whatagreatprod_test.h5
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod/test
    output: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod/dl1_proton_whatagreatprod_test.h5
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing/whatagreatprod/test
    output: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing/whatagreatprod/dl1_gamma-diffuse_whatagreatprod_test.h5
  train_pipe:
  - input:
      gamma: 
        /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing/whatagreatprod/dl1_gamma-diffuse_whatagreatprod_train.h5
      proton: 
        /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod/dl1_proton_whatagreatprod_train.h5
    output: 
      /fefs/aswg/data/models/20200629_prod5_trans_80/zenith_20deg/south_pointing/whatagreatprod
  dl1_to_dl2:
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.0deg/dl1_gamma_whatagreatprod_test.h5
    path_model: 
      /fefs/aswg/data/models/20200629_prod5_trans_80/zenith_20deg/south_pointing/whatagreatprod
    output: 
      /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.0deg
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.4deg/dl1_gamma_whatagreatprod_test.h5
    path_model: 
      /fefs/aswg/data/models/20200629_prod5_trans_80/zenith_20deg/south_pointing/whatagreatprod
    output: 
      /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.4deg
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing/whatagreatprod/dl1_electron_whatagreatprod_test.h5
    path_model: 
      /fefs/aswg/data/models/20200629_prod5_trans_80/zenith_20deg/south_pointing/whatagreatprod
    output: 
      /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing/whatagreatprod
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod/dl1_proton_whatagreatprod_test.h5
    path_model: 
      /fefs/aswg/data/models/20200629_prod5_trans_80/zenith_20deg/south_pointing/whatagreatprod
    output: 
      /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod
  - input: 
      /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing/whatagreatprod/dl1_gamma-diffuse_whatagreatprod_test.h5
    path_model: 
      /fefs/aswg/data/models/20200629_prod5_trans_80/zenith_20deg/south_pointing/whatagreatprod
    output: 
      /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing/whatagreatprod
  dl2_to_sensitivity:
  - input:
      gamma_file: 
        /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.4deg/dl2_gamma_whatagreatprod_test.h5
      proton_file: 
        /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod/dl2_proton_whatagreatprod_test.h5
      electron_file: 
        /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing/whatagreatprod/dl2_electron_whatagreatprod_test.h5
    output: 
      /fefs/aswg/data/mc/IRF/20200629_prod5_trans_80/zenith_20deg/south_pointing/whatagreatprod/off0.0deg/sensitivity_whatagreatprod_off0.0deg.fits.gz
  - input:
      gamma_file: 
        /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.4deg/dl2_gamma_whatagreatprod_test.h5
      proton_file: 
        /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod/dl2_proton_whatagreatprod_test.h5
      electron_file: 
        /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing/whatagreatprod/dl2_electron_whatagreatprod_test.h5
    output: 
      /fefs/aswg/data/mc/IRF/20200629_prod5_trans_80/zenith_20deg/south_pointing/whatagreatprod/off0.4deg/sensitivity_whatagreatprod_off0.4deg.fits.gz
  dl2_to_irfs:
  - input:
      gamma_file: 
        /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing/whatagreatprod/dl2_gamma-diffuse_whatagreatprod_test.h5
      proton_file: 
        /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod/dl2_proton_whatagreatprod_test.h5
      electron_file: 
        /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing/whatagreatprod/dl2_electron_whatagreatprod_test.h5
    output: 
      /fefs/aswg/data/mc/IRF/20200629_prod5_trans_80/zenith_20deg/south_pointing/whatagreatprod/diffuse/irf_whatagreatprod_diffuse.fits.gz
    options: ''
  - input:
      gamma_file: 
        /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.4deg/dl2_gamma_whatagreatprod_test.h5
      proton_file: 
        /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod/dl2_proton_whatagreatprod_test.h5
      electron_file: 
        /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing/whatagreatprod/dl2_electron_whatagreatprod_test.h5
    output: 
      /fefs/aswg/data/mc/IRF/20200629_prod5_trans_80/zenith_20deg/south_pointing/whatagreatprod/off0.0deg/irf_whatagreatprod_off0.0deg.fits.gz
    options: --point-like
  - input:
      gamma_file: 
        /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/whatagreatprod/off0.4deg/dl2_gamma_whatagreatprod_test.h5
      proton_file: 
        /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/whatagreatprod/dl2_proton_whatagreatprod_test.h5
      electron_file: 
        /fefs/aswg/data/mc/DL2/20200629_prod5_trans_80/electron/zenith_20deg/south_pointing/whatagreatprod/dl2_electron_whatagreatprod_test.h5
    output: 
      /fefs/aswg/data/mc/IRF/20200629_prod5_trans_80/zenith_20deg/south_pointing/whatagreatprod/off0.4deg/irf_whatagreatprod_off0.4deg.fits.gz
    options: --point-like
