########
#Configuration file for pulsar analysis using ptiming_ana
#######

###############################################################
##################### CPHASE PARAMS ###########################
###############################################################
cphase_setting:
   tel: lst 
   use_interpolation: True


###############################################################
##################### GENERAL PARAMS ##########################
###############################################################

# -------- FILE DIRECTORY -----------
pulsar_file_dir: '/fefs/aswg/workspace/analysis-school-2024/pulsar/Notebook2/Crab/DL3_pulsar/'
results_output_directory: './output/spectral_results/' #Replace this with your working directory please!!
DL4_directory: './output/OGIP/' #Replace this with your working directory please!!

target:
  name: Crab
  ra: 83.633
  dec: 22.01


# -------- REGIONS ---------

phase_regions:
  Bkg: [0.52,0.87]
  P1: [0,0.026,0.983,1]
  P2: [0.377,0.422]
  P1+P2: [0,0.026,0.377,0.422, 0.983,1]
  P3: [0.026,0.377]
  
  

###############################################################
##################### PHASEOGRAM TOOLS ########################
###############################################################


flags:
  src_dependent: False #Set to true if using src-dependent DL2 files
  DL2_format: False #Set to True if using DL2 files
  fits_format: False #Set to True if using FERMI data

cuts:
  energy_dependent_theta: False #True if apply energy-dep cuts on DL2 files
  filter_data: True
  include_DL2_extra_cuts: False #True if apply cuts on DL2 files
  zd_range: [0,35] 
  max_rad: 0.32 
  extra_cuts:
    energy_dependent: False #True if energy-dep cuts (set the energy binning at the end)
    energy: 0
    theta: 0.2
    alpha:  15
    intensity: 50
    gammaness: 0.5
    energy_binning: [0,0.02,1000]



#-------- BINNING--------------
#Binning to be used in the phaseogram
#
phase_binning:
  xmin: 0
  xmax: 1
  nbins: 50
  custom_binning: False
  binning: [0,0.1,0.2]

#Time interval to update statistics
time_binning:
   run_time_analysis: True
   units: h
   tint: 2

#Energy binning for the phaseogram energy-dependent study
energy_binning:
   run_energy_analysis: True
   do_diff: True #Set to True if want to calculate statistics for data in each energy bin (i.e 50 GeV < E < 80 GeV)
   do_integral: True # Set to True if want to calculate statistics for data above each energy edge (i.e E>50 GeV)
   units: GeV
   emin: 20
   emax: 100
   nbins: 3



# --------- PHASEOGRAM MODEL-----------
# Fitting of the phaseogram given a model
fitting:
   run_fitting: True
   model: dgaussian   # Choose among gaussian, dgaussian, asym_dgaussian, double_lorentz
   binned: True


results:
   save_results: True
   output_file: './output/phaseogram_results/results.pdf' #Replace this with a path in your working directory


###############################################################
##################### SPECTRAL TOOLS ##########################
###############################################################


reader:
  energy_dependent_theta: False
  max_rad: 0.2
  zd_range: [0,50]
  use_DL4: False #Set to True if wants to read the DL4 files (hence no reduction of the data will be done)
  save_DL4: True #Set to True if wants to save the DL4 files computed during the analysis

energy_geometry: #Geometry on true energy and reco energy for gammapy. True energy should be larger
  real:
    emin: 0.003
    emax: 50
    units: 'TeV'
    nbinning: 100
  reco:
    emin: 0.01
    emax: 10
    units: 'TeV'
    nbinning: 40
    
analysis_extra_settings:
  stacked: True
  use_safe_mask: False

#Model and energy interval used for the fitting. Only PL for the moment
spectral_fitting:
  emin: 20
  emax: 200
  units: 'GeV'
  model: 'PowerLaw'
    
#Number of spectral points in the SED
spectral_points:
  emin: 20
  emax: 200
  units: 'GeV'
  number_points: 4  #If bins_per_decade is not False, this parameter has no effect.
  bins_per_decade: False #Set to False if only want to set the total number_points
  min_ts: 1.5
  

  
